version: "2"
services:
  db:
    image: "postgres:latest"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/citas
    ports:
      - "8010:8010"
    depends_on:
      - db
