# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('almuerzo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Calendario cita',
                'verbose_name_plural': 'Calendarios de cita',
            },
        ),
        migrations.CreateModel(
            name='CitaCancelada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.IntegerField(choices=[(1, 'Mejoria'), (2, 'Sin tiempo'), (3, 'Otro motivo')])),
            ],
            options={
                'verbose_name': 'Cita cancelada',
                'verbose_name_plural': 'Citas canceladas',
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('entidad', models.IntegerField(choices=[(1, 'Particular'), (2, 'Medisanitas'), (3, 'Colsanitas')])),
                ('reprogramar', models.BooleanField(default=False)),
                ('cancelar', models.BooleanField(default=False)),
                ('estado', models.IntegerField(choices=[(1, 'Vigente'), (2, 'Cancelada'), (3, 'Vencida'), (4, 'Asistida')], default=1, verbose_name='Estado cita')),
                ('confirmacion', models.IntegerField(blank=True, choices=[(1, 'Confirmado'), (2, 'Cancelado')], null=True, verbose_name='Confirmaci\xf3n de cita')),
            ],
            options={
                'verbose_name': 'Cita m\xe9dica',
                'verbose_name_plural': 'Citas medicas',
            },
        ),
        migrations.CreateModel(
            name='CitaReprogramada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('responsable_cambio', models.BooleanField(choices=[(False, 'Medico'), (True, 'Paciente')], verbose_name='Responsable del cambio')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica')),
            ],
            options={
                'verbose_name': 'Cita reprogramada',
                'verbose_name_plural': 'Citas reprogramadas',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=15, verbose_name='Tel\xe9fono celular')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direcci\xf3n')),
                ('nit', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DuracionCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_r', models.IntegerField(verbose_name='Minutos restantes')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica')),
            ],
            options={
                'verbose_name': 'Duraci\xf3n cita',
                'verbose_name_plural': 'Duraciones de citas',
            },
        ),
        migrations.CreateModel(
            name='PagoCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.IntegerField(blank=True, default=0)),
                ('modalidad', models.IntegerField(choices=[(1, 'Consultorio'), (2, 'Virtual')])),
            ],
            options={
                'verbose_name': 'Procedimiento m\xe9dico',
                'verbose_name_plural': 'Procedimientos m\xe9dicos',
            },
        ),
    ]
