# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.ProcedimientoMedico'),
        ),
        migrations.AddField(
            model_name='citacancelada',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica'),
        ),
    ]
