# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170828_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariocita',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
