# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_calendariocita_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariocita',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asignacioncita',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
