# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20170917_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncita',
            options={'verbose_name': 'Asignaci\xf3n de cita', 'verbose_name_plural': 'Asignaciones de citas'},
        ),
        migrations.AlterModelOptions(
            name='duracioncita',
            options={'verbose_name': 'Duraci\xf3n cita', 'verbose_name_plural': 'Duraci\xf3n cita'},
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='cancelar',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='reprogramar',
        ),
    ]
