# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170917_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncita',
            name='calendario',
        ),
        migrations.RemoveField(
            model_name='asignacioncita',
            name='cita',
        ),
        migrations.AlterModelOptions(
            name='citacancelada',
            options={'verbose_name': 'Cancerlar cita', 'verbose_name_plural': 'Cancelar cita'},
        ),
        migrations.AlterModelOptions(
            name='citareprogramada',
            options={'verbose_name': 'Reprogramar cita', 'verbose_name_plural': 'Reprogramar cita'},
        ),
        migrations.AddField(
            model_name='citacancelada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citamedica',
            name='calendario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.CalendarioCita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citamedica',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citareprogramada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citacancelada',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica'),
        ),
        migrations.AlterField(
            model_name='citareprogramada',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CitaMedica'),
        ),
        migrations.DeleteModel(
            name='AsignacionCita',
        ),
    ]
