# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20170917_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='cancelado',
        ),
    ]
