# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_citamedica_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='hora_maxima',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
