# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20170922_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citacancelada',
            name='cita',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='cancelar',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='fecha_calendario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='fecha_canelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelaci\xf3n'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='motivo',
            field=models.IntegerField(blank=True, choices=[(1, 'Mejoria'), (2, 'Sin tiempo'), (3, 'Otro motivo')], null=True, verbose_name='Motivo de cancelaci\xf3n'),
        ),
        migrations.AddField(
            model_name='citareprogramada',
            name='calendario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.CalendarioCita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimientomedico',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='calendario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.CalendarioCita'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Vigente'), (2, 'Cancelada'), (3, 'Vencida')], default=1, verbose_name='Estado cita'),
        ),
        migrations.AlterField(
            model_name='citareprogramada',
            name='responsable_cambio',
            field=models.BooleanField(choices=[(False, 'Medico'), (True, 'Paciente')], default=False, verbose_name='Responsable del cambio'),
        ),
        migrations.DeleteModel(
            name='CitaCancelada',
        ),
    ]
