"""
Django settings for Citas project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nd&phi^#5v*p5kw5@5hh05@7t!%tjyovltub@&r=e3pbg#&iup'
APIKEY = "isbFMRz3wZTwp22bGV2POnAFrM"
MERCHANTID = 673242
ACCOUNTID = 675923
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ORIGIN = "*"

# Application definition

INSTALLED_APPS = [
    'material.theme.purple',
    'material',
    'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios.apps.UsuariosConfig',
    'agenda.apps.AgendaConfig',
    'adb.apps.AdbConfig',
    'supra',
    'cuser'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cuser.middleware.CuserMiddleware'
]

ROOT_URLCONF = 'Citas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Citas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dranilsa_citas',
        'USER': 'dranilsa_user',
        'PASSWORD': 'Citas96522569',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
           'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home2/dranilsa/public_html/app/Citas/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home2/dranilsa/public_html/app/Citas/media/'

# Email settings
ADMINS = [('Mario', 'mariobarrpach@gmail.com')]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
#EMAIL_HOST = 'box5027.bluehost.com'
#EMAIL_PORT = 465
EMAIL_HOST_USER = 'info@dranilsaarias.com'
EMAIL_HOST_PASSWORD = 'nilsaArias2017@'

DJANGO_LOG_LEVEL=DEBUG
# Logging
LOGGING = {
 'version': 1,
 'disable_existing_loggers': False,
 'formatters': {
     'verbose': {
         'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
     },
     'simple': {
         'format': '%(levelname)s %(message)s'
     },
 },
 'handlers': {
     'console': {
         'level': 'INFO',
         'class': 'logging.StreamHandler',
         'formatter': 'simple'
     },
     'mail_admins': {
         'level': 'ERROR',
         'class': 'django.utils.log.AdminEmailHandler',
     }
 },
 'loggers': {
     'django': {
         'handlers': ['console'],
         'propagate': True,
         'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
     },
     'django.request': {
         'handlers': ['mail_admins'],
         'level': 'ERROR',
         'propagate': True,
     }
 }
}
