# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.IntegerField(choices=[(1, 'C\xe9dula'), (2, 'Pasaporte'), (3, 'C\xe9dula de extranjeria')], verbose_name='Tipo de identificaci\xf3n')),
                ('identificacion', models.CharField(max_length=120, unique=True, verbose_name='N\xfamero de indentificaci\xf3n')),
                ('fecha_nacimiento', models.DateField()),
                ('numero_registro', models.CharField(max_length=120, verbose_name='N\xfamero de registro profesional')),
                ('nombre_u', models.CharField(max_length=120, verbose_name='Nombre de universidad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Tel\xe9fono celular')),
                ('especialidad', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.IntegerField(choices=[(1, 'C\xe9dula'), (2, 'Tarjeta de identidad'), (3, 'C\xe9dula de extranjeria'), (4, 'Registro Civil')], verbose_name='Tipo de identificaci\xf3n')),
                ('identificacion', models.CharField(max_length=120, unique=True, verbose_name='N\xfamero de indentificaci\xf3n')),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(max_length=120)),
                ('profesion', models.CharField(max_length=120, verbose_name='Profesi\xf3n')),
                ('nombre_a', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre completo acudiente')),
                ('cedula_a', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cedula acudiente')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono celular')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
