# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170828_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'M\xe9dico', 'verbose_name_plural': 'M\xe9dicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='medico',
            name='identificacion',
            field=models.CharField(max_length=120, unique=True, verbose_name='N\xb0 de indentificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numero_registro',
            field=models.CharField(max_length=120, verbose_name='N\xb0 registro profesional'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Profesi\xf3n'),
        ),
    ]
