# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170904_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
