# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicidadMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('imagen', models.ImageField(upload_to='publicidad')),
            ],
            options={
                'verbose_name': 'Publicidad m\xf3vil',
                'verbose_name_plural': 'Publicidad m\xf3vil',
            },
        ),
    ]
